### PR TITLE
Some PNG filenames do not match database names

### PR DESCRIPTION
**Pull request by yo6snap**
I remark some PNG are not synced with Retroarch database. 
For now, I've done the renaming work with one game: Zillion.

**Related Issue**
I added some game naming issues [Here](https://github.com/libretro-thumbnails/Sega_-_Master_System_-_Mark_III/issues/6)

**Reviewer**
- @RobLoach 

### Retroarch database VS No-intro one
Before renaming I check if Retroarch database is synced with No-intro one: It is **OK**.
from [No-Intro](https://datomatic.no-intro.org/index.php?page=show_record&s=26&n=0445):
> File: Zillion (USA, Europe) (Rev 1).sms
> Size:	131072
> CRC32:	5718762C   selected
> MD5:	D4BF9E7BCF9A48DA53785D2AE7BC4270
> SHA-1:	3AAB3E95DAC0FA93612DA20CF525DBA4DC4CA6BA

from [RetroArch](https://github.com/libretro/libretro-database/blob/master/metadat/no-intro/Sega%20-%20Master%20System%20-%20Mark%20III.dat):
```
game (
	name "Zillion (USA, Europe) (Rev 1)"
	description "Zillion (USA, Europe) (Rev 1)"
	rom ( name "Zillion (USA, Europe) (Rev 1).sms" size 131072 crc 5718762C md5 D4BF9E7BCF9A48DA53785D2AE7BC4270 sha1 3AAB3E95DAC0FA93612DA20CF525DBA4DC4CA6BA )
)
```
=> All database fields (i.e.: name, size, checksums) matches.

### RetroArch database game name VS Thumbnails directory filename
The glue between RetroArch database and thumbnails is the name field: It is **KO**

Database game name:
`Zillion (USA, Europe) (Rev 1)`

Thumbnail directory game filename:
`Zillion (USA) (Rev 1).png`

=> So thumbnail will never be fetched from RetroArch frontend

### Next contributions ?
Are you OK I continue renaming work on Sega - Master System - Mark III directory ? 
(and so, I will create an another pull request for that)

### CODE REVIEW

**Comment by Hawaka743** [comment]
**I think it's Ok to continue**, but I don't have admin rights over this repository, so marking my name under "reviewers" was a bit pointless.

**Comment by yo6snap** [comment]
I've just taking account of your reply. I've removed your ID from the reviewers list ;)

> I think it's Ok to continue.

I love the Sega Master System machine (I owned before).
In the past, I owned all the cartridges, carts and boxes I mentioned in related issue.
I want to contribute to keep these files synced with RetroArch database.

**Comment by RobLoach** [comment]
Thanks for the fix!

**Comment by yo6snap** [comment]
You're welcome!

When do you plan:
1. to merge this repository to corresponding submodule located at [libretro-thumbnails/libretro-thumbnails](https://github.com/libretro-thumbnails/libretro-thumbnails) ?
2. to pack thumbnails and put them to production server ? (I saw the last update on http://thumbnailpacks.libretro.com was on 10-Sep-2019)

Is there a fixed frequency to achieve that ? 
Or these updates are driven by events ?

**Pull request merged**
